SOURCE_NAME="Guardian"
SOURCE_DESCRIPTION="The Guardian"
declare -A FEEDS=(
  [World]="https://www.theguardian.com/world/rss"
  [US]="https://www.theguardian.com/us-news/rss"
  [Technology]="https://www.theguardian.com/uk/technology/rss"
  [Science]="https://www.theguardian.com/science/rss"
  [Business]="https://www.theguardian.com/uk/business/rss"
  [Environment]="https://www.theguardian.com/uk/environment/rss"
  [Books]="https://www.theguardian.com/books/rss"
)
