SOURCE_NAME="NPR"
SOURCE_DESCRIPTION="NPR"
declare -A FEEDS=(
  [TopStories]="https://feeds.npr.org/1001/rss.xml"
  [World]="https://feeds.npr.org/1004/rss.xml"
  [Politics]="https://feeds.npr.org/1014/rss.xml"
  [Business]="https://feeds.npr.org/1006/rss.xml"
  [Science]="https://feeds.npr.org/1007/rss.xml"
  [Technology]="https://feeds.npr.org/1019/rss.xml"
  [Health]="https://feeds.npr.org/1128/rss.xml"
)
