SOURCE_NAME="NYT"
SOURCE_DESCRIPTION="New York Times"
declare -A FEEDS=(
  [HomePage]="https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml"
  [World]="https://rss.nytimes.com/services/xml/rss/nyt/World.xml"
  [US]="https://rss.nytimes.com/services/xml/rss/nyt/US.xml"
  [Politics]="https://rss.nytimes.com/services/xml/rss/nyt/Politics.xml"
  [Business]="https://rss.nytimes.com/services/xml/rss/nyt/Business.xml"
  [Technology]="https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml"
  [Science]="https://rss.nytimes.com/services/xml/rss/nyt/Science.xml"
  [Health]="https://rss.nytimes.com/services/xml/rss/nyt/Health.xml"
  [Arts]="https://rss.nytimes.com/services/xml/rss/nyt/Arts.xml"
  [Opinion]="https://rss.nytimes.com/services/xml/rss/nyt/Opinion.xml"
)
