SOURCE_NAME="WSJ"
SOURCE_DESCRIPTION="Wall Street Journal"
declare -A FEEDS=(
  [World]="https://feeds.content.dowjones.io/public/rss/RSSWorldNews"
  [US]="https://feeds.content.dowjones.io/public/rss/RSSUSnews"
  [Business]="https://feeds.content.dowjones.io/public/rss/WSJcomUSBusiness"
  [Markets]="https://feeds.content.dowjones.io/public/rss/RSSMarketsMain"
  [Economy]="https://feeds.content.dowjones.io/public/rss/socialeconomyfeed"
  [Technology]="https://feeds.content.dowjones.io/public/rss/RSSWSJD"
  [Opinion]="https://feeds.content.dowjones.io/public/rss/RSSOpinion"
)
